Created work about sections
thasipablo/Personal-Portfolio pull request #2
Opened 2023-06-02 22:20 UTC by thasipablo

What I did:

- Added recent works section. A card composed section for each work.
- Added about me section
   This section has two sub-sections: a tech stack section and a contact section holding a form
- Added footer section

2023-06-02 23:11 UTC, usorfaitheloho requested changes
> Hi @thasipablo  ,
> 
> Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!

 ![](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966) [ ](https://camo.githubusercontent.com/679757134a8fee76cfe1941f9f3ecb0e0cf56dd02da4498268ce31f0dacdfca3/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)
> 
> ## Highlights
> * Good design ✔️
> * Descriptive pull request ✔️
> * Used GitHub flow ✔️
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 23:11 UTC, usorfaitheloho commented on index.html
> +          <h1 class="section-title">
You did well with your project and your design is close to the figma template given. please for Google search optimization and accessibility reasons, it's always advisable to use one `h1` tag for your project, so kindly effect the changes for these sections(works and about) of your project highlighted,since you already have the `h1` tag in your headline section😄 . please make this changes from lines 78 till 215

2023-06-02 23:11 UTC, usorfaitheloho commented on index.html
> +              I can help you build a product , feature or website Look through some of my work and experience! If you like what you see and have a project you need coded, don’t hesitate to contact me
kindly use a `p` tag for this paragraph to show good semantic usage and understanding of your code 😄

2023-06-02 23:11 UTC, usorfaitheloho commented on index.html
> +    </footer>
you did well going beyond the requirement for this milestone, it shows that you can put in a lot of work into your project ,please since this isnt part of this milestone, you can copy it to another branch and remove it from this branch so that when its time for this `contact` section the reviewer can make necessary changes 😄

2023-06-02 23:11 UTC, usorfaitheloho commented on style.css
> +
Kindly implement these design changes for the works section of your project so youthe  have a better UI and a good attention to details : 

- [ ] the heading for the section `My recent Works` have a line under it in the deisgn given please implement this change for your design 😄 

Figma design :
![image](https://github.com/thasipablo/Personal-Portfolio/assets/20537712/29cb71d2-15d9-402c-bbaf-358074fd7f83)

Your design :
![image](https://github.com/thasipablo/Personal-Portfolio/assets/20537712/cc565787-6dfe-4e82-82ce-fee37e9f5ae7)

2023-06-02 23:11 UTC, usorfaitheloho commented on style.css
> +}
The button in the `about me ` section should have the text `get my resume` as seen in the design given and not `see project` as seen in your design 

figma design :

![image](https://github.com/thasipablo/Personal-Portfolio/assets/20537712/a609ea0e-80bf-4caa-af54-0f0b2c12891e)

Your design :
![image](https://github.com/thasipablo/Personal-Portfolio/assets/20537712/00198e86-a946-42f3-99c6-e9ea04a1144d)

2023-06-03 11:08 UTC, vickymarz requested changes
Hi @thasipablo, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- This review should have been invalidated by the previous reviewer for not following the correct GitHub flow. so kindly ensure that you always create your pull request from the `feature `branch to your `main` branch as not following this will lead to invalidation next time.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 11:08 UTC, vickymarz commented on index.html
> +            <hp class="about-me-sub-title">
- [ ] I see you tried to make the changes requested to use the `<p>` tag for the paragraph, but I see you were using `<hp>` instead. Kindly change `<hp>` to `<p>` tag

2023-06-03 12:02 UTC, shahadat3669 approved these changes
Hi @thasipablo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Highlights

-  Linters are passing 👍
-  Good PR Title👍
- Good PR description👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 16:26 UTC, merged